### ISSUE TITLE
Bug when use checkbox in table

### ISSUE THREAD

**Issue by jazz7381** [Dimonka2/flatform#3]
There a bug when checkbox in row was clicked. It check all the checkbox inside the row in table. And when i click actual check all in header, it not working. 

i use laravel 8

**Comment by Dimonka2** [comment]
I guess the checkbox is a Livewire checkbox. In order to use Livewire checkboxes you need to have a unique IDs for checkboxes in order to make them working properly. If you can share some code examples maybe I can help you to resolve your issue.
