### ISSUE TITLE
Laravel 8 Support

### ISSUE THREAD

**Issue by shepherdscribe** [Dimonka2/flatform#4]
<img width="1435" alt="Screen Shot 2021-05-20 at 5 56 08 PM" src="https://user-images.githubusercontent.com/62448059/118959180-aafdf300-b994-11eb-8aef-bf9cf4e5638a.png">

Hi can you please add Laravel 8 compatibility?

**Comment by Dimonka2** [comment]
Hi, 
Your error was not about Laravel 8  it was more about PHP 8 support. 
I have added PHP 8 to composer and it seems to work.
